### Hämta alla ordrar
GET {{$dotenv ORDER_SERVICE_URL}}/admin/orders
Content-Type: application/json
Authorization: Bearer {{$dotenv ORDER_SERVICE_ADMIN_AUTH_TOKEN}}

### Hämta en användares alla ordrar
GET {{$dotenv ORDER_SERVICE_URL}}/orders/
Authorization: Bearer {{$dotenv ORDER_SERVICE_USER_AUTH_TOKEN}}

### Skapa en ny order
POST {{$dotenv ORDER_SERVICE_URL}}/orders
Content-Type: application/json
Authorization: Bearer {{$dotenv ORDER_SERVICE_USER_AUTH_TOKEN}}

{
  "shipping_address": "Privet Drive 4, Little Whinging, Surrey, England"
}

### Radera en order
DELETE {{$dotenv ORDER_SERVICE_URL}}/admin/delete/10
Content-Type: application/json
Authorization: Bearer {{$dotenv ORDER_SERVICE_ADMIN_AUTH_TOKEN}}